//Report Bug Actions.
export const LOAD_REPORTBUG = 'LOAD_REPORTBUG';
export const SAVE_REPORTBUG = 'SAVE_REPORTBUG';
export const LOAD_REPORTBUG_PENDING = 'LOAD_REPORTBUG_PENDING';
export const LOAD_REPORTBUG_FULFILLED = 'LOAD_REPORTBUG_FULFILLED';
export const LOAD_REPORTBUG_REJECTED = 'LOAD_REPORTBUG_REJECTED';
export const UPDATE_REPORTBUG = 'UPDATE_REPORTBUG';
